config/routes.rb
Rails.application.routes.draw do
  resources :admins
  resources :workers
  resources :departaments
  resources :buckets
  resources :superadmins

  get "/bucket", to: "buckets#new"
  post "/bucket", to: "buckets#create"
  get "/departament", to:"departaments#index"
  get "/signup",   to:"workers#new"
  post '/signup',  to:"workers#create"
  get "/workers", to: "admins#workers"


  resources :sessions, only: [:new, :create, :destroy]
  get "/", to:"sessions#new"
  post "/session", to:"sessions#create"

  delete "/signout", to:"sessions#destroy"

  delete "/buckets", to:"buckets#destroy"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/departament.rb
class Departament < ApplicationRecord
   has_many :worker
   has_one :admin
   after_destroy :delete_workers_and_admins

   validates(:name, presence: true, length: {maximum: 50})


   def Departament.make_unapproved
      Departament.update_all(if_schedule_on_current_week_is_approve:false)
   end

   def delete_workers_and_admins
   	self.worker.destroy_all if  self.worker
   	self.admin.destroy if self.admin
   end

end

app/controllers/departaments_controller.rb
class DepartamentsController < ApplicationController
  before_action :set_departament, only: [:show, :edit, :update, :destroy]
  before_action :is_superadmin, only: [:show, :edit, :update, :destroy, :index]

  def is_superadmin
    if cookies[:superadmin] == "true"
    else
      if current_worker
        redirect_to current_worker
      else
        redirect_to '/'
      end
    end
  end

  def index
    @departaments = Departament.all
  end

  def show
  end

  def new
    @departament = Departament.new(if_schedule_on_current_week_is_approve:false)
  end

  def edit
  end

  def create
    @departament = Departament.new(departament_params)
    respond_to do |format|
      if @departament.save
        format.html { redirect_to @departament, notice: 'Departament was successfully created.' }
        format.json { render :show, status: :created, location: @departament }
      else
        format.html { render :new }
        format.json { render json: @departament.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @departament.update(departament_params)
        format.html { redirect_to @departament, notice: 'Departament was successfully updated.' }
        format.json { render :show, status: :ok, location: @departament }
      else
        format.html { render :edit }
        format.json { render json: @departament.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @departament.destroy
    respond_to do |format|
      format.html { redirect_to departaments_url, notice: 'Departament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_departament
      @departament = Departament.find(params[:id])
    end

    def departament_params
      params.require(:departament).permit(:name,:if_schedule_on_current_week_is_approve)
    end
end

app/helpers/departaments_helper.rb
module DepartamentsHelper
end

app/views/departaments/_form.html.erb
<%= form_for(@departament) do |f| %>

    <% if @departament.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(@departament.errors.count, "error") %> prohibited this departament from being saved:</h2>

      <ul>
      <% @departament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departaments/edit.html.erb
<h1>Editing Departament</h1>

<%= render 'form', departament: @departament %>

<%= link_to 'Show', @departament %> |
<%= link_to 'Back', departaments_path %>

app/views/departaments/index.html.erb
<p id="notice"><%= notice %></p>
<%cookies[:page] = "Departament"%>
<h1>Отделы</h1>

<table class="s_dep_table">
  <thead>
    <tr>
      <th>Имя</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departaments.each do |departament| %>
      <tr>
        <td><%= departament.name %></td>
        <td><%= link_to 'Показать', departament %></td>
        <td><%= link_to 'Редактировать', edit_departament_path(departament) %></td>
        <td><%= link_to 'Удалить', departament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="link_new"><%= link_to 'Новый отдел', new_departament_path %></div>

app/views/departaments/new.html.erb
<h1>New Departament</h1>

<%= render 'form', departament: @departament %>

<%= link_to 'Back', departaments_path %>

app/views/departaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @departament.name %>
</p>

<%= link_to 'Edit', edit_departament_path(@departament) %> |
<%= link_to 'Back', departaments_path %>