config/routes.rb
Rails.application.routes.draw do
  resources :admins
  resources :workers
  resources :departaments
  resources :buckets
  resources :superadmins

  get "/bucket", to: "buckets#new"
  post "/bucket", to: "buckets#create"
  get "/departament", to:"departaments#index"
  get "/signup",   to:"workers#new"
  post '/signup',  to:"workers#create"
  get "/workers", to: "admins#workers"


  resources :sessions, only: [:new, :create, :destroy]
  get "/", to:"sessions#new"
  post "/session", to:"sessions#create"

  delete "/signout", to:"sessions#destroy"

  delete "/buckets", to:"buckets#destroy"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header>
  <div id="name"><strong>InstructorApp</strong></div>
  <% if signed_in? %>
      <div><%= link_to "Выход", signout_path, method: "delete"%></div>
      <% if cookies[:admin] == "false" && cookies[:superadmin] == "false"  %>
          <div <%if cookies[:page] == "My schedule"%> class = "testClass" <% end %> ><%= link_to "Расписание", '/bucket' %></div>
      <% end %>
      <% if cookies[:admin] == "true" %>
          <div <%if cookies[:page] == "Workers"%> class = "testClass" <% end %> ><%= link_to "Сотрудники", "/workers", type:"button"%></div>
          <div <%if cookies[:page] == "Timetable"%> class = "testClass" <% end %> ><%= link_to "Расписание", admins_path%></div>
      <% end %>
      <% if cookies[:admin] == "true" %>
          <div <%if cookies[:page] == "Settings"%> class = "testClass" <% end %> ><%= link_to "Профиль", edit_admin_path(current_worker) %></div>
      <% elsif  cookies[:admin] == "false" && cookies[:superadmin] == "false" %>
          <div <%if cookies[:page] == "Profile"%> class = "testClass" <% end %>><%= link_to "Профиль", current_worker %></div>
          <div <%if cookies[:page] == "Settings"%> class = "testClass" <% end %>><%= link_to "Настройки", edit_worker_path(current_worker) %></div>
      <% end %>
      <% if cookies[:superadmin] == "true" %>
          <div <%if cookies[:page] == "Departament"%> class = "testClass" <% end %> >
            <%= link_to "Отделы", '/departament'%>
          </div>
          <div <%if cookies[:page] == "Admins"%> class = "testClass" <% end %>>
            <%= link_to "Админы", superadmins_path%>
          </div>
      <% end %>
  <% else%>
      <div <%if cookies[:page] == "Sign up"%> class = "testClass" <% end %>><%= link_to "Регистрация", 'signup'%></div>
      <div <%if cookies[:page] == "Sign in"%> class = "testClass" <% end %>><%= link_to "Вход",'/', type:"button"%></div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


  <head>
  <title>Instructor App</title>
    
    <title><%=yield :title%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <div><%=render 'layouts/header'%>
      <script>
        $('body').show();
        $('.version').text(NProgress.version);
        NProgress.start();
        setTimeout(function() { NProgress.done(); $('.fade').removeClass('out'); }, 1000);
      </script>
    </div>
    <div class = "container down" >
      <% flash.each do |message_type, message| %>
        <div class = "alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
    </div>

    <%= yield %>
    
      
      
  

    <%#= debug(params) if Rails.env.development? %>
    
  </body>


</html>